# Generated by Django 3.2.4 on 2023-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeGpt_students', '0003_auto_20230512_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraint',
            field=models.CharField(default='', max_length=100),
        ),
    ]
