# Generated by Django 4.2.1 on 2023-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeGpt_students', '0004_question_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='constraint',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
