# Generated by Django 3.2.4 on 2023-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeGpt_students', '0005_alter_question_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expected',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='testcases',
            field=models.JSONField(),
        ),
    ]
