# Generated by Django 3.2.4 on 2023-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeGpt_students', '0006_auto_20230514_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='device',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.JSONField(default={}),
        ),
    ]
